### ISSUE TITLE
Improve sliding performance

### ISSUE THREAD

**Issue by bhrgunatha** [codereport/racket-algorithms#10]
Nice library.  

`sliding` compares the `length` of the remaining list to `size` in every recursive call.  
`length` has to count every item in the whole list each time which for larger lists can add up.    

I propose a helper procedure that uses the initial length of the list and reduces that value at each recursive call.  

```
(define (sliding-new xs size [step 1])
  (define (tail-call xs L)
    (if (>= size L)
        (list xs)
        (cons (take xs size)
              (tail-call (drop xs step)
                         (- L step)))))
  (tail-call xs (length xs)))
```

On my clunky, old machine:

```
(equal? (time (sliding (range 100000) 17 3))
        (time (sliding-new (range 100000) 17 3)))

> cpu time: 2181 real time: 2182 gc time: 21
> cpu time: 7 real time: 7 gc time: 3
> #t
```

**Comment by codereport** [comment]
Thanks, will update the sliding implementation.
