### ISSUE TITLE
Add Replicate

### ISSUE THREAD

**Issue by ElectricCoffee** [codereport/racket-algorithms#11]
It would be neat if APL's replicate existed in this library.

Here's an example implementation:

```
#lang racket

(require algorithms)

; flattens just one level, instead of all the way
; I forget what it's called in APL
(define (flatten1 xs) (foldr append '() xs))

(define (replicate cs xs)
  (define (replicate-one c xs)
    (map (λ (x) (make-list c x)) xs))
  (define (replicate-many cs xs)
    (zip-with make-list cs xs))

  (flatten1
   (cond
     [(and (cons? cs) (= 1 (length cs))) (replicate-one (car cs) xs)]
     [(cons? cs) (replicate-many cs xs)]
     [else (replicate-one cs xs)])))

(define dataset '(a b c d e))

(replicate 2 dataset)            ; '(a a b b c c d d e e)
(replicate '(3) dataset)         ; '(a a a b b b c c c d d d e e e)
(replicate '(0 1 2 3 4) dataset) ; '(b c c d d d e e e e)
```

Adding a flatmap would be nice also

**Comment by codereport** [comment]
I have added this function but a slightly different version without the rank polymorphism. Replicate will only take two lists, and the lengths need to be equal. No other algorithms are rank-polymorphic so it doesn't make sense for this one to be.

**Comment by ElectricCoffee** [comment]
What about then also adding the scalar version as well, as a separate function? I imagine replicating each value in the list by a scalar amount could be useful.
