### ISSUE TITLE
adjacent-map arguments order

### ISSUE THREAD

**Issue by filiplajszczak** [codereport/racket-algorithms#9]
`adjacent-map` takes `lst` and `proc`. On the one hand it is confusing as regular `map` takes `proc` and `lst` so it would be good to change the order, on the other hand that would be backward incompatible breaking change. Maybe it's better to introduce breaking changes sooner than later?

It's something I noticed while porting it to Guile, and I changed the order there.

**Comment by codereport** [comment]
I agree. `lst` should be last. I will merge an update later today.
